-- =====================================================================
-- FULL SCHEMA MIGRATION SCRIPT
-- Run this in the SQL Editor of your NEW Supabase project.
-- Order: extensions -> tables -> functions -> triggers -> RLS -> policies -> indexes
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. EXTENSIONS
-- ---------------------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
-- pg_stat_statements and supabase_vault are managed by Supabase itself,
-- no need to create them manually (already present on every project).

-- ---------------------------------------------------------------------
-- 2. TABLES  (created in dependency order)
-- ---------------------------------------------------------------------

CREATE TABLE public.roles (
  role_id uuid NOT NULL DEFAULT gen_random_uuid(),
  role_name text NOT NULL UNIQUE,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  CONSTRAINT roles_pkey PRIMARY KEY (role_id),
  CONSTRAINT roles_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);

CREATE TABLE public.users (
  user_id uuid NOT NULL,
  username text NOT NULL UNIQUE,
  mobile_no text NOT NULL,
  role_id uuid,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'active'::text, 'deactivated'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  CONSTRAINT users_pkey PRIMARY KEY (user_id),
  CONSTRAINT users_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT users_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.roles(role_id),
  CONSTRAINT users_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT users_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id)
);

CREATE TABLE public.audit_log (
  log_id bigint GENERATED BY DEFAULT AS IDENTITY,
  table_name text NOT NULL,
  record_id text NOT NULL,
  action text NOT NULL CHECK (action = ANY (ARRAY['insert'::text, 'update'::text, 'delete'::text])),
  changed_by uuid,
  changed_by_username text,
  changed_at timestamp with time zone NOT NULL DEFAULT now(),
  old_data jsonb,
  new_data jsonb,
  CONSTRAINT audit_log_pkey PRIMARY KEY (log_id),
  CONSTRAINT audit_log_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES auth.users(id)
);

CREATE TABLE public.notices (
  notice_id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  message text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  CONSTRAINT notices_pkey PRIMARY KEY (notice_id),
  CONSTRAINT notices_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT notices_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id)
);

CREATE TABLE public.student_master (
  reg_no text NOT NULL,
  name text NOT NULL,
  father_name text NOT NULL,
  mobile_no text NOT NULL,
  class text NOT NULL CHECK (class = ANY (ARRAY['4'::text, '5'::text, '6'::text, '7'::text, '8'::text, '9'::text, '10'::text, '11-arts'::text, '11-science'::text, '12-arts'::text, '12-science'::text])),
  admission_date date NOT NULL DEFAULT CURRENT_DATE,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'deactivated'::text])),
  is_readmission boolean NOT NULL DEFAULT false,
  remark text,
  recorded_by uuid,
  recorded_at timestamp with time zone NOT NULL DEFAULT now(),
  deactivate_date date,
  deactivated_by uuid,
  deactivated_at timestamp with time zone,
  updated_by uuid,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  reactivated_at date,
  gender text CHECK (gender IS NULL OR (gender = ANY (ARRAY['Male'::text, 'Female'::text]))),
  section text,
  roll_no text,
  CONSTRAINT student_master_pkey PRIMARY KEY (reg_no),
  CONSTRAINT student_master_recorded_by_fkey FOREIGN KEY (recorded_by) REFERENCES auth.users(id),
  CONSTRAINT student_master_deactivated_by_fkey FOREIGN KEY (deactivated_by) REFERENCES auth.users(id),
  CONSTRAINT student_master_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id)
);

CREATE TABLE public.fee_master (
  fee_id uuid NOT NULL DEFAULT gen_random_uuid(),
  student_reg_no text NOT NULL,
  type text NOT NULL CHECK (type = ANY (ARRAY['admission'::text, 'readmission'::text, 'monthly'::text])),
  amount numeric NOT NULL,
  remark text,
  recorded_by uuid,
  recorded_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT fee_master_pkey PRIMARY KEY (fee_id),
  CONSTRAINT fee_master_recorded_by_fkey FOREIGN KEY (recorded_by) REFERENCES auth.users(id),
  CONSTRAINT fee_master_student_reg_no_fkey FOREIGN KEY (student_reg_no) REFERENCES public.student_master(reg_no)
);

CREATE TABLE public.fee_categories (
  category_id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  active boolean NOT NULL DEFAULT true,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT fee_categories_pkey PRIMARY KEY (category_id),
  CONSTRAINT fee_categories_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);

CREATE TABLE public.fee_receipts (
  receipt_id uuid NOT NULL DEFAULT gen_random_uuid(),
  student_reg_no text NOT NULL,
  fee_type text NOT NULL CHECK (fee_type = ANY (ARRAY['monthly'::text, 'admission_readmission'::text, 'other'::text])),
  for_months text[],
  category_id uuid,
  amount_cash numeric NOT NULL DEFAULT 0,
  amount_bank numeric NOT NULL DEFAULT 0,
  amount_phonepe numeric NOT NULL DEFAULT 0,
  discount numeric NOT NULL DEFAULT 0,
  remark text,
  recorded_by uuid,
  recorded_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT fee_receipts_pkey PRIMARY KEY (receipt_id),
  CONSTRAINT fee_receipts_student_reg_no_fkey FOREIGN KEY (student_reg_no) REFERENCES public.student_master(reg_no),
  CONSTRAINT fee_receipts_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.fee_categories(category_id),
  CONSTRAINT fee_receipts_recorded_by_fkey FOREIGN KEY (recorded_by) REFERENCES auth.users(id)
);

CREATE TABLE public.departments (
  department_id uuid NOT NULL DEFAULT gen_random_uuid(),
  department_name text NOT NULL,
  department_type text NOT NULL CHECK (department_type = ANY (ARRAY['teaching'::text, 'non_teaching'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  CONSTRAINT departments_pkey PRIMARY KEY (department_id),
  CONSTRAINT departments_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT departments_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id),
  CONSTRAINT departments_department_name_department_type_key UNIQUE (department_name, department_type)
);

CREATE TABLE public.staff (
  staff_id uuid NOT NULL DEFAULT gen_random_uuid(),
  staff_name text NOT NULL,
  mobile_no text,
  staff_type text NOT NULL CHECK (staff_type = ANY (ARRAY['teaching'::text, 'non_teaching'::text, 'guest'::text])),
  department_id uuid,
  joining_date date NOT NULL,
  remark text,
  is_active boolean NOT NULL DEFAULT true,
  deactivated_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  CONSTRAINT staff_pkey PRIMARY KEY (staff_id),
  CONSTRAINT staff_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(department_id),
  CONSTRAINT staff_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT staff_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id)
);

CREATE TABLE public.staff_salary_history (
  salary_history_id uuid NOT NULL DEFAULT gen_random_uuid(),
  staff_id uuid NOT NULL,
  salary_amount numeric NOT NULL,
  effective_month date NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  CONSTRAINT staff_salary_history_pkey PRIMARY KEY (salary_history_id),
  CONSTRAINT staff_salary_history_staff_id_fkey FOREIGN KEY (staff_id) REFERENCES public.staff(staff_id),
  CONSTRAINT staff_salary_history_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT staff_salary_history_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id),
  CONSTRAINT staff_salary_history_staff_id_effective_month_key UNIQUE (staff_id, effective_month)
);

CREATE TABLE public.salary_month_adjustments (
  adjustment_id uuid NOT NULL DEFAULT gen_random_uuid(),
  staff_id uuid NOT NULL,
  salary_month date NOT NULL,
  absent_days numeric NOT NULL DEFAULT 0,
  bonus_amount numeric NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  CONSTRAINT salary_month_adjustments_pkey PRIMARY KEY (adjustment_id),
  CONSTRAINT salary_month_adjustments_staff_id_fkey FOREIGN KEY (staff_id) REFERENCES public.staff(staff_id),
  CONSTRAINT salary_month_adjustments_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT salary_month_adjustments_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id),
  CONSTRAINT salary_month_adjustments_staff_id_salary_month_key UNIQUE (staff_id, salary_month)
);

CREATE TABLE public.salary_payments (
  payment_id uuid NOT NULL DEFAULT gen_random_uuid(),
  voucher_no text NOT NULL UNIQUE,
  payment_date date NOT NULL,
  staff_id uuid NOT NULL,
  salary_month date NOT NULL,
  amount numeric NOT NULL,
  discount numeric NOT NULL DEFAULT 0,
  mode text NOT NULL CHECK (mode = ANY (ARRAY['cash'::text, 'bank'::text, 'phonepe'::text])),
  remark text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  CONSTRAINT salary_payments_pkey PRIMARY KEY (payment_id),
  CONSTRAINT salary_payments_staff_id_fkey FOREIGN KEY (staff_id) REFERENCES public.staff(staff_id),
  CONSTRAINT salary_payments_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT salary_payments_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id)
);

-- ---------------------------------------------------------------------
-- 3. FUNCTIONS
-- ---------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.current_role_name()
 RETURNS text
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select r.role_name
  from public.users u
  join public.roles r on r.role_id = u.role_id
  where u.user_id = auth.uid()
    and u.status = 'active'
  limit 1;
$function$;

CREATE OR REPLACE FUNCTION public.current_username()
 RETURNS text
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select username from public.users where user_id = auth.uid() limit 1;
$function$;

CREATE OR REPLACE FUNCTION public.is_admin()
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select public.current_role_name() = 'admin';
$function$;

CREATE OR REPLACE FUNCTION public.set_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  new.updated_at = now();
  return new;
end;
$function$;

-- ---------------------------------------------------------------------
-- 4. TRIGGERS
-- ---------------------------------------------------------------------

CREATE TRIGGER trg_departments_updated_at
  BEFORE UPDATE ON public.departments
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_notices_updated_at
  BEFORE UPDATE ON public.notices
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_salary_month_adjustments_updated_at
  BEFORE UPDATE ON public.salary_month_adjustments
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_salary_payments_updated_at
  BEFORE UPDATE ON public.salary_payments
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_staff_updated_at
  BEFORE UPDATE ON public.staff
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_staff_salary_history_updated_at
  BEFORE UPDATE ON public.staff_salary_history
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_student_master_updated_at
  BEFORE UPDATE ON public.student_master
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_users_updated_at
  BEFORE UPDATE ON public.users
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ---------------------------------------------------------------------
-- 5. ENABLE ROW LEVEL SECURITY
-- ---------------------------------------------------------------------

ALTER TABLE public.roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.student_master ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fee_master ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fee_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fee_receipts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.departments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.staff ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.staff_salary_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.salary_month_adjustments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.salary_payments ENABLE ROW LEVEL SECURITY;

-- ---------------------------------------------------------------------
-- 6. POLICIES
-- ---------------------------------------------------------------------

-- roles
CREATE POLICY roles_select ON public.roles FOR SELECT
  USING (auth.uid() IS NOT NULL);
CREATE POLICY roles_insert ON public.roles FOR INSERT
  WITH CHECK (is_admin());
CREATE POLICY roles_update ON public.roles FOR UPDATE
  USING (is_admin());

-- users
CREATE POLICY users_select_self ON public.users FOR SELECT
  USING ((auth.uid() = user_id) OR is_admin());
CREATE POLICY users_insert_self ON public.users FOR INSERT
  WITH CHECK (auth.uid() = user_id);
CREATE POLICY users_update_self_or_admin ON public.users FOR UPDATE
  USING ((auth.uid() = user_id) OR is_admin());

-- audit_log
CREATE POLICY audit_select_admin ON public.audit_log FOR SELECT
  USING (is_admin());
CREATE POLICY audit_insert ON public.audit_log FOR INSERT
  WITH CHECK (auth.uid() IS NOT NULL);

-- notices
CREATE POLICY notices_select ON public.notices FOR SELECT
  USING (current_role_name() IS NOT NULL);
CREATE POLICY notices_insert ON public.notices FOR INSERT
  WITH CHECK (current_role_name() = ANY (ARRAY['admin'::text, 'editor'::text, 'viewer'::text]));
CREATE POLICY notices_update ON public.notices FOR UPDATE
  USING (current_role_name() = ANY (ARRAY['admin'::text, 'editor'::text]));
CREATE POLICY notices_delete ON public.notices FOR DELETE
  USING (current_role_name() = ANY (ARRAY['admin'::text, 'editor'::text]));

-- student_master
CREATE POLICY student_master_select ON public.student_master FOR SELECT
  USING (current_role_name() IS NOT NULL);
CREATE POLICY student_master_insert ON public.student_master FOR INSERT
  WITH CHECK (current_role_name() = ANY (ARRAY['admin'::text, 'editor'::text, 'viewer'::text]));
CREATE POLICY student_master_update ON public.student_master FOR UPDATE
  USING (current_role_name() = ANY (ARRAY['admin'::text, 'editor'::text]));
CREATE POLICY student_master_delete ON public.student_master FOR DELETE
  USING (current_role_name() = ANY (ARRAY['admin'::text, 'editor'::text]));

-- fee_master
CREATE POLICY fee_master_select ON public.fee_master FOR SELECT
  USING (current_role_name() IS NOT NULL);
CREATE POLICY fee_master_insert ON public.fee_master FOR INSERT
  WITH CHECK (current_role_name() = ANY (ARRAY['admin'::text, 'editor'::text, 'viewer'::text]));

-- fee_categories
CREATE POLICY fee_categories_select ON public.fee_categories FOR SELECT
  USING (current_role_name() IS NOT NULL);
CREATE POLICY fee_categories_insert ON public.fee_categories FOR INSERT
  WITH CHECK (current_role_name() = ANY (ARRAY['admin'::text, 'editor'::text, 'viewer'::text]));
CREATE POLICY fee_categories_update ON public.fee_categories FOR UPDATE
  USING (current_role_name() = ANY (ARRAY['admin'::text, 'editor'::text]));

-- fee_receipts
CREATE POLICY fee_receipts_select ON public.fee_receipts FOR SELECT
  USING (current_role_name() IS NOT NULL);
CREATE POLICY fee_receipts_insert ON public.fee_receipts FOR INSERT
  WITH CHECK (current_role_name() = ANY (ARRAY['admin'::text, 'editor'::text, 'viewer'::text]));
CREATE POLICY fee_receipts_update ON public.fee_receipts FOR UPDATE
  USING (current_role_name() = ANY (ARRAY['admin'::text, 'editor'::text]));
CREATE POLICY fee_receipts_delete ON public.fee_receipts FOR DELETE
  USING (current_role_name() = ANY (ARRAY['admin'::text, 'editor'::text]));

-- departments
CREATE POLICY departments_select ON public.departments FOR SELECT
  USING (current_role_name() IS NOT NULL);
CREATE POLICY departments_insert ON public.departments FOR INSERT
  WITH CHECK (current_role_name() = ANY (ARRAY['admin'::text, 'accountant'::text, 'manager'::text]));
CREATE POLICY departments_update ON public.departments FOR UPDATE
  USING (current_role_name() = 'admin'::text);
CREATE POLICY departments_delete ON public.departments FOR DELETE
  USING (current_role_name() = 'admin'::text);

-- staff
CREATE POLICY staff_select ON public.staff FOR SELECT
  USING (current_role_name() IS NOT NULL);
CREATE POLICY staff_insert ON public.staff FOR INSERT
  WITH CHECK (current_role_name() = ANY (ARRAY['admin'::text, 'accountant'::text, 'manager'::text]));
CREATE POLICY staff_update ON public.staff FOR UPDATE
  USING (current_role_name() = 'admin'::text);
CREATE POLICY staff_delete ON public.staff FOR DELETE
  USING (current_role_name() = 'admin'::text);

-- staff_salary_history
CREATE POLICY staff_salary_history_select ON public.staff_salary_history FOR SELECT
  USING (current_role_name() IS NOT NULL);
CREATE POLICY staff_salary_history_insert ON public.staff_salary_history FOR INSERT
  WITH CHECK (current_role_name() = ANY (ARRAY['admin'::text, 'accountant'::text, 'manager'::text]));
CREATE POLICY staff_salary_history_update ON public.staff_salary_history FOR UPDATE
  USING (current_role_name() = 'admin'::text);
CREATE POLICY staff_salary_history_delete ON public.staff_salary_history FOR DELETE
  USING (current_role_name() = 'admin'::text);

-- salary_month_adjustments
CREATE POLICY salary_month_adjustments_select ON public.salary_month_adjustments FOR SELECT
  USING (current_role_name() IS NOT NULL);
CREATE POLICY salary_month_adjustments_insert ON public.salary_month_adjustments FOR INSERT
  WITH CHECK (current_role_name() = ANY (ARRAY['admin'::text, 'accountant'::text, 'manager'::text]));
CREATE POLICY salary_month_adjustments_update ON public.salary_month_adjustments FOR UPDATE
  USING (current_role_name() = ANY (ARRAY['admin'::text, 'accountant'::text, 'manager'::text]));
CREATE POLICY salary_month_adjustments_delete ON public.salary_month_adjustments FOR DELETE
  USING (current_role_name() = 'admin'::text);

-- salary_payments
CREATE POLICY salary_payments_select ON public.salary_payments FOR SELECT
  USING (current_role_name() IS NOT NULL);
CREATE POLICY salary_payments_insert ON public.salary_payments FOR INSERT
  WITH CHECK (current_role_name() = ANY (ARRAY['admin'::text, 'accountant'::text, 'manager'::text]));
CREATE POLICY salary_payments_update ON public.salary_payments FOR UPDATE
  USING (current_role_name() = 'admin'::text);
CREATE POLICY salary_payments_delete ON public.salary_payments FOR DELETE
  USING (current_role_name() = 'admin'::text);

-- ---------------------------------------------------------------------
-- 7. EXTRA INDEXES (not already created implicitly by PK/UNIQUE constraints)
-- ---------------------------------------------------------------------

CREATE INDEX idx_users_role ON public.users USING btree (role_id);
CREATE INDEX idx_users_status ON public.users USING btree (status);

CREATE INDEX idx_audit_table_record ON public.audit_log USING btree (table_name, record_id);
CREATE INDEX idx_audit_changed_at ON public.audit_log USING btree (changed_at DESC);

CREATE INDEX idx_fee_master_reg_no ON public.fee_master USING btree (student_reg_no);
CREATE INDEX idx_fee_master_reg_type_time ON public.fee_master USING btree (student_reg_no, type, recorded_at DESC);

CREATE INDEX idx_fee_receipts_reg_no ON public.fee_receipts USING btree (student_reg_no);
CREATE INDEX idx_fee_receipts_type_time ON public.fee_receipts USING btree (fee_type, recorded_at);
CREATE INDEX idx_fee_receipts_recorded_at ON public.fee_receipts USING btree (recorded_at);

-- =====================================================================
-- END OF SCRIPT
-- =====================================================================
